# Generated by Django 5.2.8 on 2025-11-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDFFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da estação pluviométrica ou localidade', max_length=200, verbose_name='Nome da Estação/Local')),
                ('city', models.CharField(help_text='Cidade onde está localizada a estação', max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Estado brasileiro (UF)', max_length=2, verbose_name='Estado')),
                ('k', models.FloatField(help_text='Parâmetro K da equação IDF', verbose_name='K')),
                ('a', models.FloatField(help_text='Expoente do tempo de retorno (TR)', verbose_name='a')),
                ('b', models.FloatField(help_text='Parâmetro b da equação IDF', verbose_name='b')),
                ('c', models.FloatField(help_text='Expoente da duração (t + b)', verbose_name='c')),
                ('duration_min', models.PositiveIntegerField(default=5, help_text='Duração mínima válida (minutos)', verbose_name='Duração mínima')),
                ('duration_max', models.PositiveIntegerField(default=1440, help_text='Duração máxima válida (minutos)', verbose_name='Duração máxima')),
                ('return_period_min', models.PositiveIntegerField(default=2, help_text='Tempo de retorno mínimo válido (anos)', verbose_name='TR mínimo')),
                ('return_period_max', models.PositiveIntegerField(default=100, help_text='Tempo de retorno máximo válido (anos)', verbose_name='TR máximo')),
                ('source', models.CharField(blank=True, help_text='Referência bibliográfica ou fonte dos dados', max_length=300, verbose_name='Fonte')),
                ('author', models.CharField(blank=True, help_text='Autor(es) do estudo', max_length=200, verbose_name='Autor(es)')),
                ('year', models.PositiveIntegerField(blank=True, help_text='Ano de publicação do estudo', null=True, verbose_name='Ano de publicação')),
                ('latitude', models.FloatField(blank=True, help_text='Latitude em graus decimais', null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, help_text='Longitude em graus decimais', null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica se a fórmula está disponível para consulta', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Fórmula IDF',
                'verbose_name_plural': 'Fórmulas IDF',
                'ordering': ['state', 'city', 'name'],
                'indexes': [models.Index(fields=['state', 'city'], name='banco_idf_i_state_77679c_idx'), models.Index(fields=['name'], name='banco_idf_i_name_ad041c_idx')],
            },
        ),
    ]
