ALTER TABLE budget_items ADD COLUMN IF NOT EXISTS parent_id UUID REFERENCES budget_items(id);
ALTER TABLE budget_items ADD COLUMN IF NOT EXISTS numbering VARCHAR(50) DEFAULT '';
ALTER TABLE budget_items ADD COLUMN IF NOT EXISTS item_type VARCHAR(20) DEFAULT 'ITEM';
